<?php declare(strict_types=1);

namespace Izzle\Pagination\Tests;

use Izzle\Pagination\Meta;
use PHPUnit\Framework\TestCase;

/**
 * Class MetaTest
 * @package Izzle\Pagination\Tests
 */
class MetaTest extends TestCase
{
    /**
     * @var Meta
     */
    protected Meta $meta;
    
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        
        $this->meta = new Meta([
            'offset' => 75,
            'perPage' => 25,
            'total' => 1621
        ]);
    }
    
    public function testCanBeInstantiatedWithData(): void
    {
        $this->assertEquals(75, $this->meta->getOffset());
        $this->assertEquals(25, $this->meta->getPerPage());
        $this->assertEquals(1621, $this->meta->getTotal());
        $this->assertEquals(76, $this->meta->getFrom());
        $this->assertEquals(100, $this->meta->getTo());
        $this->assertEquals(4, $this->meta->getCurrentPage());
        $this->assertEquals(65, $this->meta->getLastPage());
    }
    
    public function testCanSetACurrentPage(): void
    {
        $this->assertEquals(75, $this->meta->getOffset());
    
        $this->meta->setCurrentPage(8);
    
        $this->assertEquals(175, $this->meta->getOffset());
        $this->assertEquals(25, $this->meta->getPerPage());
        $this->assertEquals(1621, $this->meta->getTotal());
        $this->assertEquals(176, $this->meta->getFrom());
        $this->assertEquals(200, $this->meta->getTo());
        $this->assertEquals(8, $this->meta->getCurrentPage());
        $this->assertEquals(65, $this->meta->getLastPage());
    }
}
