<?php declare(strict_types=1);

namespace Izzle\Pagination\Tests;

use Izzle\Pagination\Meta;
use PHPUnit\Framework\TestCase;

/**
 * Class MetaTest
 * @package Izzle\Pagination\Tests
 */
class MetaTest extends TestCase
{
    /**
     * @var Meta
     */
    protected Meta $meta;
    
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    
        $data = json_decode(file_get_contents(__DIR__ . '/mocks/meta.json'), true, 512, JSON_THROW_ON_ERROR);
        
        $this->meta = new Meta($data);
    }
    
    public function testCanBeInstantiatedWithData(): void
    {
        self::assertEquals(75, $this->meta->getOffset());
        self::assertEquals(25, $this->meta->getPerPage());
        self::assertEquals(1621, $this->meta->getTotal());
        self::assertEquals(76, $this->meta->getFrom());
        self::assertEquals(100, $this->meta->getTo());
        self::assertEquals(4, $this->meta->getCurrentPage());
        self::assertEquals(65, $this->meta->getLastPage());
    }
    
    public function testCanSetACurrentPage(): void
    {
        self::assertEquals(75, $this->meta->getOffset());
    
        $this->meta->setCurrentPage(8);
    
        self::assertEquals(175, $this->meta->getOffset());
        self::assertEquals(25, $this->meta->getPerPage());
        self::assertEquals(1621, $this->meta->getTotal());
        self::assertEquals(176, $this->meta->getFrom());
        self::assertEquals(200, $this->meta->getTo());
        self::assertEquals(8, $this->meta->getCurrentPage());
        self::assertEquals(65, $this->meta->getLastPage());
    }
}
