<?php declare(strict_types=1);

namespace Izzle\Pagination\Tests;

use Izzle\Pagination\Pagination;
use Izzle\Pagination\Tests\Models\Dummy;
use PHPUnit\Framework\TestCase;

class PaginationTest extends TestCase
{
    /**
     * @var Pagination
     */
    protected Pagination $pagination;
    
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        
        $data = json_decode(file_get_contents(__DIR__ . '/mocks/pagination.json'), true, 512, JSON_THROW_ON_ERROR);
        
        $this->pagination = new Pagination($data);
    }
    
    public function testHaveLinks(): void
    {
        $this->assertNotEmpty($this->pagination->getLinks());
        $this->assertEquals('http://www.foo.bar/?page=3', $this->pagination->getLinks()->getNext());
    }
    
    public function testHaveMetas(): void
    {
        $this->assertNotEmpty($this->pagination->getMeta());
        $this->assertEquals(4, $this->pagination->getMeta()->getCurrentPage());
    }
    
    public function testCanAddData(): void
    {
        $this->assertCount(1, $this->pagination->getData());
        $this->pagination->addData(new Dummy([2, 'test']));
        $this->assertCount(2, $this->pagination->getData());
    }
}
